apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugins
  annotations:
    github.com/project-slug: cloud-eda/backstage-plugins
spec:
  type: other
  lifecycle: unknown
  owner: user:default/test-user
